
service: sqs
 
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
 
functions:
  hello:
    handler: index.put
    events:
      - sqs: arn:aws:sqs:ap-northeast-2:556123699728:stock_queue
