apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reqsys-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reqsys-backend
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 40

  # 간단 설정 방법
  # kubectl autoscale deployment demo-flask-backend --cpu-percent=30 --min=1 --max=5